# Generated by Django 4.2.3 on 2023-07-23 13:32

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_passwordentry_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordentry',
            name='password',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
